version: '3.8'

services:
  dashboard:
    ports:
      - "8000:8000"    # Dashboard web interface

  mcp-server-1:
    ports:
      - "8001:8001"    # Laboratory Adventure MCP HTTP server

  mcp-server-2:
    ports:
      - "8002:8001"    # Simple Adventure MCP HTTP server on different host port

  mcp-server-3:
    ports:
      - "8003:8001"    # Dungeon Crawler MCP HTTP server on different host port
